---
abstract: 'OOP interface to the Plesk XML API (http://www.parallels.com/en/products/plesk/).'
author:
  - 'Ivan Sokolov <ivsokolov@cpan.org>'
build_requires:
  Test::LongString: 0
  Test::More: 0
  URI: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: API-Plesk
provides:
  API::Plesk:
    file: lib/API/Plesk.pm
    version: 2.00_1
requires:
  Carp: 0
  Data::Dumper: 0
  HTTP::Request: 0
  LWP::UserAgent: 0
  XML::Fast: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 2.00_1
